version: '3.9'
services:
  postgresql:
    image: duyme18/postgres:17
    container_name: postgres_server
    hostname: 43b1b4d397d4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: duyme18/keycloak:26.0.7
    container_name: keycloak_server
    hostname: 5b0b5e6bc3b9
    command: start-dev
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgresql
      KC_DB_URL_DATABASE: mydatabase
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_RUN_IN_CONTAINER: true
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  postgres_data:
  keycloak_data:
